### ISSUE TITLE
Peer-Peer Code Review

### ISSUE THREAD

**Issue by egichuhis** [hamzaw9/portfolio#13]
Comments:

- Kindly update your README file with `Javascript` in the `Techstacks` section
- It is advisable to wrap your Javascript code and implementation in a `Function` for easier update, modification and even inheritance

**Comment by sagieramos** [comment]
Nice job :+1: , You have really done well, but I notice that you use multiple click event listener in your code. It would be better to use Event delegation. :wink: 
Event delagation is a techique used to improve performance and reduce memory usage when handling events on multiple elements within a container.

Imagine you have a list of items on a webpage, like a to-do list or a collection of blog posts. Each item in the list is clickable, and you want to do something when users click on any of those items. Now, you have two options on how to handle these clicks:

- Option 1: You can individually attach a click event listener to each item on the list. It works, but if you have many items, it can be quite a lot of work. Plus, it can slow down your webpage because it needs to keep track of all these separate event listeners.

- Option 2 (the smarter way): Instead of assigning a click listener to each item, you attach just one listener to the whole list itself (the parent). It's like having a watchful eye on the entire list. When a user clicks on any item, the click event is "delegated" or passed up to the parent element, which then figures out which specific item was clicked. It's like the parent acts as a mediator and knows how to handle the click event for its children.

By doing this, you save time and effort, especially if your list is long or if you add items dynamically. You also make your webpage faster because it only has to manage one event listener instead of many. It's like having a group chat instead of sending individual messages to each friend.

In your code, instead of assigning a click event handler to each item like `menu`, `closeMenu`, and so on, you just have one event listener on the whole list. When a user clicks on any item, the event "bubbles up" to the list, and the event handler figures out which item was clicked and does the right thing.

**Comment by egichuhis** [comment]
Good stuff @sagieramos , today I have learnt a lot from you. Thanks!
